"""add account to transactions

Revision ID: 50cd9ec42164
Revises: 580d3f77bed6
Create Date: 2026-08-30 00:40:58.414845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cd9ec42164'
down_revision: Union[str, Sequence[str], None] = '580d3f77bed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
